# Generated by Django 3.2.9 on 2021-11-16 11:04

import cinema.custom_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardClient',
            fields=[
                ('id', models.
                 PositiveIntegerField(primary_key=True,
                                      serialize=False,
                                      validators=[cinema.
                                                  custom_validators.
                                                  non_negative_number,
                                                  cinema.custom_validators.
                                                  non_zero_number])),
                ('nume', models.TextField(validators=[cinema.custom_validators.
                                                      name_validate])),
                ('prenume', models.TextField(validators=[cinema.
                                                         custom_validators.
                                                         name_validate])),
                ('CNP', models.TextField(max_length=13, unique=True,
                                         validators=[cinema.
                                                     custom_validators.
                                                     CNP_validate])),
                ('data_nasterii', models.DateField()),
                ('data_inregistrarii', models.DateField()),
                ('puncte', models.
                 PositiveIntegerField(validators=[cinema.custom_validators.
                                                  non_negative_number])),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.
                 PositiveIntegerField(primary_key=True,
                                      serialize=False,
                                      validators=[cinema.
                                                  custom_validators.
                                                  non_negative_number,
                                                  cinema.
                                                  custom_validators.
                                                  non_zero_number])),
                ('titlu', models.TextField(max_length=256)),
                ('an_aparitie', models.
                 PositiveIntegerField(validators=[cinema.custom_validators.
                                                  movie_year])),
                ('pret', models.
                 PositiveIntegerField(validators=[cinema.custom_validators.
                                                  non_negative_number])),
                ('in_program', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.
                 PositiveIntegerField(primary_key=True, serialize=False,
                                      validators=[cinema.
                                                  custom_validators.
                                                  non_negative_number,
                                                  cinema.custom_validators.
                                                  non_zero_number])),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('id_card_client', models.ForeignKey(blank=True, null=True,
                                                     on_delete=django.db.
                                                     models.
                                                     deletion.SET_NULL,
                                                     to='cinema.cardclient')),
                ('id_film', models.
                 ForeignKey(limit_choices_to={'in_program': True},
                            on_delete=django.db.models.deletion.CASCADE,
                            to='cinema.film')),
            ],
        ),
    ]
