# Generated by Django 3.2.9 on 2021-12-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20211118_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardclient',
            name='puncte',
            field=models.PositiveIntegerField(),
        ),
    ]
